CREATE DATABASE gestion_cinema;

CREATE USER cinema_usr WITH PASSWORD 'cinema_pwd';

GRANT CONNECT ON DATABASE gestion_cinema TO cinema_usr;

GRANT USAGE ON SCHEMA public TO cinema_usr;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO cinema_usr;

GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO cinema_usr;

ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO cinema_usr;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT USAGE, SELECT ON SEQUENCES TO cinema_usr;
